#!/usr/bin/perl -w

use strict;
use lib "lib";
use Data::Dump;
use LWP;

push(@Data::Dump::FILTERS, sub {
    my($ctx, $object) = @_;
    print $ctx->container_class, " ", $ctx->container_self, "\n" if $ctx->container_class;
    if ($ctx->is_scalar && $$object && $$object =~ /^\d+$/) {
	return { replace_with => $$object * 2, comment => "\n Used to be $$object" };
    }
    if ($ctx->is_scalar && $$object) {
	return { use_repr => "..." };
    }
    if (!$ctx->class && $ctx->reftype eq "SCALAR" && defined($$object) && length($$object) > 20) {
	return { replace_with => substr($$object, 0, 10) . "..." . substr($$object, -5) }
    }
    if ($ctx->object_isa("LWP::UserAgent")) {
	return { replace_class => "", comment => "LWP::UserAgent" }
    }
    if ($ctx->object_isa("URI")) {
	return { replace_with => "<$object>", comment => "Actually a URI subclass" };
    }
    if ($ctx->object_isa("HTTP::Message")) {
	return { hide_keys => [qw(_request)] };
    }
    return;
});



my $ua = LWP::UserAgent->new;
my $res = $ua->get("http://www.example.com");

dd $ua;
dd $res;
